# Generated by Django 4.0.1 on 2022-01-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='tags',
        ),
    ]
