# Generated by Django 4.0.1 on 2022-03-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coment',
            new_name='Comment',
        ),
    ]
