# Generated by Django 4.0.1 on 2022-03-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_rename_coment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.clase'),
        ),
    ]
