# Generated by Django 4.0.1 on 2022-03-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_comment_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='url del sitio'),
        ),
    ]
