# Generated by Django 4.0.1 on 2022-03-16 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_curso_clase_clase_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='slug',
            new_name='clase_slug',
        ),
        migrations.RenameField(
            model_name='clase',
            old_name='clase_curso',
            new_name='curso',
        ),
    ]
