# Generated by Django 4.0.1 on 2022-03-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_remove_student_profile_picture_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='thumbnail',
            field=models.ImageField(upload_to='media/clases/thumbnail'),
        ),
    ]
