# Generated by Django 4.0.1 on 2022-03-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_clase_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
