# Generated by Django 4.0.3 on 2022-03-26 06:48

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_clase_subtitle_alter_clase_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
